# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160123_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='standard1',
        ),
        migrations.RemoveField(
            model_name='school',
            name='standard2',
        ),
    ]
